create table public.empathy_metrics (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    metric_type text not null check (
        metric_type in (
            'good_deeds',
            'connecting_time'
        )
    ),
    value integer not null
);
-- Enable Row Level Security
alter table public.empathy_metrics enable row level security;
-- Create policy
create policy "Enable all operations for authenticated users" on public.empathy_metrics for all using (true) with check (true);